services:
  mysqldb:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: patient-registration
      MYSQL_USER: admin
      MYSQL_PASSWORD: lightit1234
      MYSQL_ROOT_PASSWORD: lightit1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet
  backend:
    container_name: backend
    build: ./backend
    image: patient-registration-backend:1.0
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysqldb
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: backend
    networks:
      - internalnet
  frontend:
    container_name: frontend
    build: ./frontend
    image: patient-registration-frontend:1.0
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - backend
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: frontend
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge